version: 0.2

env:
  variables:
    ACCOUNT_ID: 314146295673
    FRONTEND_REPO: frontend
    BACKEND_REPO: backend
    FRONTEND_DIR: student-teacher-app
    BACKEND_DIR: backend
    K8S_MANIFEST_DIR: DevOps/Kubernetes-Manifests
    DOCKER_HUB_USERNAME: ashutoshsanghi
    DOCKER_HUB_PASSWORD: dckr_pat_JlGl968JH7EPE2qmM6I2PT1Mr-4
    HOST_US_EAST_1: bXlzcWxkYXRhYmFzZS5jdnVzd20wbTZic2MudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
    HOST_US_WEST_1: bXlzcWxkYXRhYmFzZS53ZXN0LnVzLmV4YW1wbGUuY29t
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing utilities...
      - yum install -y jq
      - echo Installing sonar-scanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.8.0.2856-linux/bin
      - sonar-scanner --version  # optional, to verify installation
  pre_build:
    commands:
      - echo Setting dynamic image tag...
      - export IMAGE_TAG=v1.${CODEBUILD_BUILD_NUMBER}
      - echo Logging in to Amazon ECR 
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - echo Installing frontend dependencies...
      - cd $FRONTEND_DIR && npm install && cd -
      - echo Installing backend dependencies...
      - cd $BACKEND_DIR && npm install && cd -
      - echo Sonar Qube
      - |
        sonar-scanner \
          -Dsonar.projectKey=capstonesonar1 \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://18.226.98.166 \
          -Dsonar.login=sqp_5c49ac5bdba6dd0461d1b58840ed1b612fe7e93b

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG $FRONTEND_DIR
      - docker tag $FRONTEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker build -t $BACKEND_REPO:$IMAGE_TAG $BACKEND_DIR
      - docker tag $BACKEND_REPO:$IMAGE_TAG ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG

      - echo Preparing Kubernetes manifest output directory...
      - mkdir -p k8s-out

      # FRONTEND
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Frontend/deployment.yaml > k8s-out/frontend-deployment.yaml
      - cp $K8S_MANIFEST_DIR/Frontend/service.yaml k8s-out/frontend-service.yaml

      # BACKEND
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG|g" $K8S_MANIFEST_DIR/Backend/deployment.yaml > k8s-out/backend-deployment.yaml
      - cp $K8S_MANIFEST_DIR/Backend/service.yaml k8s-out/backend-service.yaml

      # DATABASE
      - cp $K8S_MANIFEST_DIR/Database/namespace.yaml k8s-out/database-namespace.yaml || true
      - |
        if [ "$REGION" = "us-east-1" ]; then
          HOST_B64=$HOST_US_EAST_1
        elif [ "$REGION" = "us-west-1" ]; then
          HOST_B64=$HOST_US_WEST_1
        else
          echo "Unsupported region: $REGION" && exit 1
        fi
      - sed "s|HOST_PLACEHOLDER|$HOST_B64|g" $K8S_MANIFEST_DIR/Database/secrets.yaml > k8s-out/database-secrets.yaml

      # INGRESS
      - cp $K8S_MANIFEST_DIR/ingress.yaml k8s-out/ingress.yaml || true

      - echo "Final list of generated Kubernetes YAML files:"
      - find k8s-out/

artifacts:
  base-directory: k8s-out
  discard-paths: yes
  files:
    - '**/*.yaml'

cache:
  paths:
    - 'student-teacher-app/node_modules/**/*'
    - 'backend/node_modules/**/*'

