apiVersion: v1
kind: Secret
metadata: 
  name: db-credentials
  namespace: mern
type: Opaque
data: 
  host: bXlzcWxkYXRhYmFzZS5jNzJnc2NxbzAxd2wudXMtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29t
  user: YWRtaW4=
  password: YWRtaW5hZG1pbg==
  database: TXlTUUxEYXRhYmFzZQ==
